name: Publish to github pages at pengson-wang/wxformat-web

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    permissions:
      issues: read
      contents: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm build
      - run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/pengson-wang/wxformat-web.git
          npx gh-pages -d build -u "github-actions-bot <support+actions@github.com>" -a -m "release" -b main
        env:
          GITHUB_TOKEN: ${{secrets.WXFORMAT_ORG_WRITE}}
